services:
  omnibus-server:
    image: ghcr.io/waterloo-rocketry/omnibus-server@sha256:104f969857a4c61a70a4f0621c11af9feafccf94775ef3ce185310f8eb1c967c
    network_mode: host
    restart: unless-stopped

  omnibus-globallog:
    image: ghcr.io/waterloo-rocketry/omnibus-globallog@sha256:6fcedde3ea72b0d49ffd7812a4ca76c21cbfb0a0e34a48e0c646574c7c8b1858
    network_mode: host
    restart: unless-stopped
    depends_on:
      - omnibus-server
    volumes:
      - ./data:/data
    command: ["--outfolder", "/data"]

  omnibus-source-ljm:
    image: ghcr.io/waterloo-rocketry/omnibus-source-ljm@sha256:2c07aa238d4b8626712f984a8a817d04ab988151993d71eb41273b8c2fb77be2
    network_mode: host
    restart: unless-stopped
    depends_on:
      - omnibus-server
    volumes:
      - ./config:/config
  
  omnibus-ws-bridge:
    image: ghcr.io/waterloo-rocketry/omnibus-ws-bridge@sha256:c20218eda368626e2be25eb6d4608ee69205ff63e12e3de31aeddcc127ec7fcc
    network_mode: host
    restart: unless-stopped
    depends_on:
      - omnibus-server
      - omnibus-ws-server

  omnibus-ws-server:
    image: ghcr.io/waterloo-rocketry/omnibus-ws-server@sha256:b43dff41c05fc83e85694dfef9e3e5a8a3d28a0ab90db31fe08c1d3fee127acf
    network_mode: host
    restart: unless-stopped
    depends_on:
      - omnibus-server

  daqms:
    image: ghcr.io/waterloo-rocketry/omnibus-daqms@sha256:433a4c4ea0bddd2d25fba356a3f2bb89c38214ef159190182886d061af331646
    restart: unless-stopped
    depends_on:
      - omnibus-server
    ports:
      - 8080:8080

  # /dev/serial/by-path/platform-xhci-hcd.0-usb-0:1.1:1.0 is the Injector CAN support board, USB Port 1 on hub
  parsley-source-injector:
    image: ghcr.io/waterloo-rocketry/omnibus-source-parsley@sha256:1c1fde8bfa0a576516e8b5eebb0b8d6aa81c2e184afdb6602ea3d9c707f61674
    restart: unless-stopped
    depends_on:
      - omnibus-server
    network_mode: host
    hostname: EGSE-INJECTOR
    devices:
      - source: /dev/serial/by-path/platform-xhci-hcd.0-usb-0:1.1:1.0
        target: /dev/ttyACM0
        permissions: rwm

  # /dev/serial/by-path/platform-xhci-hcd.0-usb-0:1.2:1.0 is the Upper CAN support board, USB Port 2 on hub
  parsley-source-upper:
    image: ghcr.io/waterloo-rocketry/omnibus-source-parsley@sha256:1c1fde8bfa0a576516e8b5eebb0b8d6aa81c2e184afdb6602ea3d9c707f61674
    restart: unless-stopped
    depends_on:
      - omnibus-server
    network_mode: host
    hostname: EGSE-UPPER
    devices:
      - source: /dev/serial/by-path/platform-xhci-hcd.0-usb-0:1.2:1.0
        target: /dev/ttyACM0
        permissions: rwm
